[build]
builder = "NIXPACKS"

[deploy]
startCommand = "./start-services.sh"
healthcheckPath = "/health"
healthcheckTimeout = 300

[[deploy.volumeMounts]]
mountPath = "/data"
name = "dashboard-data"

[environments.production]
variables = { }

[environments.development]
variables = { }