[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd railway-app && uvicorn main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 300

[environments.production]
variables = { }

[environments.development]
variables = { }